const http = require('http');

const server = http.createServer((req, res) => {
        if(req.url == "/") {
            res.end("<h1> welcome to the home pages </h1> <h1>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt quas in laboriosam maxime? Assumenda animi a dolorem alias iusto eius ea ullam deserunt, ipsam ex quam, voluptates nostrum minima maxime ipsum eaque aut optio? Tempore, molestiae reprehenderit modi nulla repellat distinctio impedit! In aliquid velit eveniet molestiae modi incidunt saepe necessitatibus, pariatur eaque iusto deserunt perspiciatis suscipit ea porro accusantium natus omnis eum magnam earum illum. Quae itaque placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos laborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos eiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissilaborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae  nobis, nemo dolorum voluptas? Perferendis delectus a quidem incidunt quaerat consectetur deserunt doloribus necessitatibus pariatur. Sit accusantium rem ex cupiditate atque ullam debitis alias modi impedit repellat veritatis quibusdam exercitationem ipsa voluptates quasi dolorum consequatur totam blanditiis nemo ducimus, quas accusamus officiis. Est officia, doloremque provident quo, dignissimos molestias quod placeat unde, hic exercitationem iure totam ullam minus expedita soluta aut eaque! Eos inventore modi magni blanditiis quidem quaerat!.</h1>");
        }
        else  if(req.url == "/index") {
            res.end("<h1> welcome to the index pages </h1> <h1>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt quas in laboriosam maxime? Assumenda animi a dolorem alias iusto eius ea ullam deserunt, ipsam ex quam, voluptates nostrum minima maxime ipsum eaque aut optio? Tempore, molestiae reprehenderit modi nulla repellat distinctio impedit! In aliquid velit eveniet molestiae modi incidunt saepe necessitatibus, pariatur eaque iusto deserunt perspiciatis suscipit ea porro accusantium natus omnis eum magnam earum illum. Quae itaque placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos laborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos eiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissilaborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae  nobis, nemo dolorum voluptas? Perferendis delectus a quidem incidunt quaerat consectetur deserunt doloribus necessitatibus pariatur. Sit accusantium rem ex cupiditate atque ullam debitis alias modi impedit repellat veritatis quibusdam exercitationem ipsa voluptates quasi dolorum consequatur totam blanditiis nemo ducimus, quas accusamus officiis. Est officia, doloremque provident quo, dignissimos molestias quod placeat unde, hic exercitationem iure totam ullam minus expedita soluta aut eaque! Eos inventore modi magni blanditiis quidem quaerat!.</h1>");
        }
        else  if(req.url == "/login") {
            res.end("<h1> welcome to the login pages </h1> <h1>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt quas in laboriosam maxime? Assumenda animi a dolorem alias iusto eius ea ullam deserunt, ipsam ex quam, voluptates nostrum minima maxime ipsum eaque aut optio? Tempore, molestiae reprehenderit modi nulla repellat distinctio impedit! In aliquid velit eveniet molestiae modi incidunt saepe necessitatibus, pariatur eaque iusto deserunt perspiciatis suscipit ea porro accusantium natus omnis eum magnam earum illum. Quae itaque placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos laborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos eiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissilaborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae  nobis, nemo dolorum voluptas? Perferendis delectus a quidem incidunt quaerat consectetur deserunt doloribus necessitatibus pariatur. Sit accusantium rem ex cupiditate atque ullam debitis alias modi impedit repellat veritatis quibusdam exercitationem ipsa voluptates quasi dolorum consequatur totam blanditiis nemo ducimus, quas accusamus officiis. Est officia, doloremque provident quo, dignissimos molestias quod placeat unde, hic exercitationem iure totam ullam minus expedita soluta aut eaque! Eos inventore modi magni blanditiis quidem quaerat!.</h1>");
        }
        else  if(req.url == "/signup") {
            res.end("<h1> welcome to the signup pages </h1> <h1>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt quas in laboriosam maxime? Assumenda animi a dolorem alias iusto eius ea ullam deserunt, ipsam ex quam, voluptates nostrum minima maxime ipsum eaque aut optio? Tempore, molestiae reprehenderit modi nulla repellat distinctio impedit! In aliquid velit eveniet molestiae modi incidunt saepe necessitatibus, pariatur eaque iusto deserunt perspiciatis suscipit ea porro accusantium natus omnis eum magnam earum illum. Quae itaque placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos laborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos eiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissilaborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae  nobis, nemo dolorum voluptas? Perferendis delectus a quidem incidunt quaerat consectetur deserunt doloribus necessitatibus pariatur. Sit accusantium rem ex cupiditate atque ullam debitis alias modi impedit repellat veritatis quibusdam exercitationem ipsa voluptates quasi dolorum consequatur totam blanditiis nemo ducimus, quas accusamus officiis. Est officia, doloremque provident quo, dignissimos molestias quod placeat unde, hic exercitationem iure totam ullam minus expedita soluta aut eaque! Eos inventore modi magni blanditiis quidem quaerat!.</h1>");
        }
        else  if(req.url == "/services") {
            res.end("<h1> welcome to the services pages </h1> <h1>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt quas in laboriosam maxime? Assumenda animi a dolorem alias iusto eius ea ullam deserunt, ipsam ex quam, voluptates nostrum minima maxime ipsum eaque aut optio? Tempore, molestiae reprehenderit modi nulla repellat distinctio impedit! In aliquid velit eveniet molestiae modi incidunt saepe necessitatibus, pariatur eaque iusto deserunt perspiciatis suscipit ea porro accusantium natus omnis eum magnam earum illum. Quae itaque placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos laborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissimos eiciendis delectus dolor, aliquid quae placeat corrupti? Accusantium nisi, aliquid perspiciatis earum mollitia repellat odio magni vitae ipsam inventore quidem sequi est ab harum sapiente cupiditate praesentium laborum facere nam id suscipit soluta recusandae! Est illum amet aspernatur nisi sed aut corrupti hic illo cumque, recusandae voluptate quisquam ipsum asperiores ratione maxime fugiat. Corporis autem dignissilaborum assumenda atque cupiditate, et neque debitis reiciendis delectus dolor, aliquid quae  nobis, nemo dolorum voluptas? Perferendis delectus a quidem incidunt quaerat consectetur deserunt doloribus necessitatibus pariatur. Sit accusantium rem ex cupiditate atque ullam debitis alias modi impedit repellat veritatis quibusdam exercitationem ipsa voluptates quasi dolorum consequatur totam blanditiis nemo ducimus, quas accusamus officiis. Est officia, doloremque provident quo, dignissimos molestias quod placeat unde, hic exercitationem iure totam ullam minus expedita soluta aut eaque! Eos inventore modi magni blanditiis quidem quaerat!.</h1>");
        }
        else{
                 res.end("<h1> not a create rount </h1>") 
})

server.listen(8091,()=>{
    console.log("server listening on port 8091");
})
